/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/wuruicheng/Desktop/Multiplayer-Three-Gallery/apps/frontend/src/modules/three/wallBlock/assets/model.glb --transform --types
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    立方體: THREE.Mesh
    立方體001: THREE.Mesh
  }
  materials: {}
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/model-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.立方體.geometry} material={nodes.立方體.material} position={[9.88, 0.47, 0.03]} scale={[1, 18, 100]} />
      <mesh geometry={nodes.立方體001.geometry} material={nodes.立方體001.material} position={[-0.11, 0.47, 10.01]} scale={[100, 18, 1]} />
    </group>
  )
}

useGLTF.preload('/model-transformed.glb')
