/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 model.glb --transform --types
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import model from "./assets/model-transformed.glb";

type GLTFResult = GLTF & {
  nodes: {
    平面: THREE.Mesh
  }
  materials: {
    材質: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(model) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.平面.geometry} material={materials.材質} />
    </group>
  )
}

useGLTF.preload(model)
